packages:
  - apps/*
  - packages/*

allowBuilds:
  "@nestjs/core": true
  "@parcel/watcher": true
  "@scarf/scarf": true
  "@swc/core": true
  core-js: false
  esbuild: true
  lefthook: true
  sharp: true
  unrs-resolver: true
  workerd: false

catalog:
  "@floating-ui/react": "^0.27.19"
  "@phosphor-icons/react": "^2.1.10"
  "@react-navigation/native": "^7.2.2"
  "@storybook/addon-ondevice-actions": "^10.6.0"
  "@storybook/react-native": "^10.6.0"
  "@storybook/react-native-web-vite": "^10.6.1"
  "@storybook/react-vite": "^10.6.1"
  "@tamagui/animations-css": "2.7.6"
  "@tamagui/animations-react-native": "2.7.6"
  "@tamagui/animations-reanimated": "2.7.6"
  "@tamagui/colors": "2.7.6"
  "@tamagui/config": "2.7.6"
  "@tamagui/constants": "2.7.6"
  "@tamagui/core": "2.7.6"
  "@tamagui/font-inter": "2.7.6"
  "@tamagui/get-font-sized": "2.7.6"
  "@tamagui/get-token": "2.7.6"
  "@tamagui/linear-gradient": "2.7.6"
  "@tamagui/logo": "2.7.6"
  "@tamagui/lucide-icons-2": "2.7.6"
  "@tamagui/metro-plugin": "2.7.6"
  "@tamagui/react-native-media-driver": "2.7.6"
  "@tamagui/react-native-svg": "2.7.6"
  "@tamagui/roving-focus": "2.7.6"
  "@tamagui/shorthands": "2.7.6"
  "@tamagui/stacks": "2.7.6"
  "@tamagui/theme-builder": "2.7.6"
  "@tamagui/themes": "2.7.6"
  "@tamagui/toast": "2.7.6"
  "@tamagui/vite-plugin": "2.7.6"
  "@tamagui/web": "2.7.6"
  "@tanstack/react-form": "^1.29.1"
  "@tanstack/react-query": "^5.100.7"
  "@tanstack/react-store": "^0.11.2"
  "@tanstack/store": "^0.11.2"
  "@testing-library/jest-dom": "^6.9.1"
  "@testing-library/react": "^16.3.2"
  "@types/node": "^24.12.4"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"
  "@typescript/native-preview": "7.0.0-dev.20260515.1"
  "@vitejs/plugin-react": "^6.0.1"
  "@vitest/coverage-v8": "^4.1.6"
  "@vxrn/color-scheme": "~1.16.5"
  dotenv: "^17.4.2"
  happy-dom: "^20.9.0"
  i18next: "^25.10.10"
  jsdom: "^29.1.1"
  lucide-react: "^1.16.0"
  matchmedia-polyfill: "^0.3.2"
  react: "^19.2.6"
  react-cookie: "^8.1.2"
  react-dom: "^19.2.6"
  react-i18next: "^16.6.6"
  react-native: "0.83.4"
  react-native-reanimated: "~4.2.1"
  react-native-svg: "15.15.4"
  react-native-web: "~0.21.2"
  storybook: "^10.6.1"
  tamagui: "2.7.6"
  typescript: "~5.9.3"
  vite: "^8.0.10"
  vitest: "^4.1.5"
  zod: "^4.3.6"
  zustand: "^5.0.12"

nodeLinker: hoisted

overrides:
  lightningcss: 1.30.1
  "@types/node": "^24.12.4"
