import type { ComboboxOption } from './index';

export const authorOptions: ComboboxOption[] = [
  { value: 'austen', label: 'Jane Austen', keywords: 'pride prejudice sense sensibility' },
  { value: 'bronte-c', label: 'Charlotte Brontë', keywords: 'jane eyre' },
  { value: 'bronte-e', label: 'Emily Brontë', keywords: 'wuthering heights' },
  { value: 'dickens', label: 'Charles Dickens', keywords: 'oliver twist great expectations' },
  {
    value: 'dostoevsky',
    label: 'Fyodor Dostoevsky',
    keywords: 'crime punishment brothers karamazov',
  },
  { value: 'tolstoy', label: 'Leo Tolstoy', keywords: 'war peace anna karenina' },
  { value: 'dumas', label: 'Alexandre Dumas', keywords: 'monte cristo musketeers' },
  { value: 'hugo', label: 'Victor Hugo', keywords: 'les miserables hunchback' },
  { value: 'twain', label: 'Mark Twain', keywords: 'huckleberry finn tom sawyer' },
  { value: 'hemingway', label: 'Ernest Hemingway', keywords: 'old man sun farewell arms' },
  { value: 'fitzgerald', label: 'F. Scott Fitzgerald', keywords: 'great gatsby' },
  { value: 'steinbeck', label: 'John Steinbeck', keywords: 'grapes wrath east eden' },
  { value: 'orwell', label: 'George Orwell', keywords: '1984 animal farm' },
  { value: 'joyce', label: 'James Joyce', keywords: 'ulysses dubliners' },
  { value: 'woolf', label: 'Virginia Woolf', keywords: 'mrs dalloway lighthouse' },
  { value: 'faulkner', label: 'William Faulkner', keywords: 'sound fury' },
  { value: 'salinger', label: 'J.D. Salinger', keywords: 'catcher rye' },
  { value: 'lee', label: 'Harper Lee', keywords: 'kill mockingbird' },
  { value: 'murakami', label: 'Haruki Murakami', keywords: 'kafka wind-up bird' },
  { value: 'garcia-marquez', label: 'Gabriel García Márquez', keywords: 'hundred years solitude' },
  { value: 'borges', label: 'Jorge Luis Borges', keywords: 'labyrinths ficciones' },
  { value: 'nabokov', label: 'Vladimir Nabokov', keywords: 'lolita' },
  { value: 'kafka', label: 'Franz Kafka', keywords: 'metamorphosis trial castle' },
  { value: 'camus', label: 'Albert Camus', keywords: 'stranger plague' },
  { value: 'sartre', label: 'Jean-Paul Sartre', keywords: 'nausea existentialism' },
  { value: 'proust', label: 'Marcel Proust', keywords: 'remembrance time' },
  { value: 'flaubert', label: 'Gustave Flaubert', keywords: 'madame bovary' },
  { value: 'zola', label: 'Émile Zola', keywords: 'germinal' },
  { value: 'balzac', label: 'Honoré de Balzac', keywords: 'comédie humaine' },
  { value: 'chekhov', label: 'Anton Chekhov', keywords: 'cherry orchard stories' },
  { value: 'gogol', label: 'Nikolai Gogol', keywords: 'dead souls overcoat' },
  { value: 'pushkin', label: 'Alexander Pushkin', keywords: 'eugene onegin' },
  { value: 'dostoevsky-notes', label: 'Fyodor Dostoevsky', keywords: 'notes underground' },
  { value: 'bulgakov', label: 'Mikhail Bulgakov', keywords: 'master margarita' },
  { value: 'solzhenitsyn', label: 'Alexander Solzhenitsyn', keywords: 'gulag archipelago' },
  { value: 'pasternak', label: 'Boris Pasternak', keywords: 'doctor zhivago' },
  { value: 'coelho', label: 'Paulo Coelho', keywords: 'alchemist' },
  { value: 'allende', label: 'Isabel Allende', keywords: 'house spirits' },
  { value: 'llosa', label: 'Mario Vargas Llosa', keywords: 'feast goat' },
  { value: 'cortazar', label: 'Julio Cortázar', keywords: 'hopscotch' },
  { value: 'neruda', label: 'Pablo Neruda', keywords: 'poetry odes' },
  { value: 'rushdie', label: 'Salman Rushdie', keywords: 'midnight children' },
  { value: 'roy', label: 'Arundhati Roy', keywords: 'god small things' },
  { value: 'lahiri', label: 'Jhumpa Lahiri', keywords: 'interpreter maladies' },
  { value: 'adichie', label: 'Chimamanda Ngozi Adichie', keywords: 'half yellow sun' },
  { value: 'achebe', label: 'Chinua Achebe', keywords: 'things fall apart' },
  { value: 'soueif', label: 'Ahdaf Soueif', keywords: 'map love' },
  { value: 'mahfouz', label: 'Naguib Mahfouz', keywords: 'cairo trilogy' },
  { value: 'oz', label: 'Amos Oz', keywords: 'tale love darkness' },
  { value: 'pamuk', label: 'Orhan Pamuk', keywords: 'museum innocence' },
  { value: 'kundera', label: 'Milan Kundera', keywords: 'unbearable lightness' },
  { value: 'hugo-notre', label: 'Victor Hugo', keywords: 'notre dame' },
  { value: 'verne', label: 'Jules Verne', keywords: 'journey center earth' },
  { value: 'wilde', label: 'Oscar Wilde', keywords: 'picture dorian gray' },
  { value: 'doyle', label: 'Arthur Conan Doyle', keywords: 'sherlock holmes' },
  { value: 'poe', label: 'Edgar Allan Poe', keywords: 'raven tell-tale' },
  { value: 'hawthorne', label: 'Nathaniel Hawthorne', keywords: 'scarlet letter' },
  { value: 'melville', label: 'Herman Melville', keywords: 'moby dick' },
  { value: 'wharton', label: 'Edith Wharton', keywords: 'age innocence' },
  { value: 'chopin', label: 'Kate Chopin', keywords: 'awakening' },
  { value: 'cather', label: 'Willa Cather', keywords: 'my antonia' },
  { value: 'bradbury', label: 'Ray Bradbury', keywords: 'fahrenheit 451' },
  { value: 'asimov', label: 'Isaac Asimov', keywords: 'foundation i robot' },
  { value: 'clarke', label: 'Arthur C. Clarke', keywords: '2001 odyssey' },
  { value: 'le-guin', label: 'Ursula K. Le Guin', keywords: 'earthsea left hand' },
  { value: 'atwood', label: 'Margaret Atwood', keywords: 'handmaid tale' },
  { value: 'lessing', label: 'Doris Lessing', keywords: 'golden notebook' },
  { value: 'morrison', label: 'Toni Morrison', keywords: 'beloved' },
  { value: 'walker', label: 'Alice Walker', keywords: 'color purple' },
  { value: 'angelou', label: 'Maya Angelou', keywords: 'know why caged' },
  { value: 'baldwin', label: 'James Baldwin', keywords: 'go tell mountain' },
  { value: 'ellison', label: 'Ralph Ellison', keywords: 'invisible man' },
  { value: 'wright', label: 'Richard Wright', keywords: 'native son' },
  { value: 'hughes', label: 'Langston Hughes', keywords: 'poetry harlem' },
  { value: 'hurston', label: 'Zora Neale Hurston', keywords: 'eyes watching' },
  { value: 'tan', label: 'Amy Tan', keywords: 'joy luck club' },
  { value: 'king', label: 'Stephen King', keywords: 'shining it' },
  { value: 'rowling', label: 'J.K. Rowling', keywords: 'harry potter' },
  { value: 'tolkien', label: 'J.R.R. Tolkien', keywords: 'lord rings hobbit' },
  { value: 'lewis', label: 'C.S. Lewis', keywords: 'narnia' },
  { value: 'carroll', label: 'Lewis Carroll', keywords: 'alice wonderland' },
  { value: 'baum', label: 'L. Frank Baum', keywords: 'wizard oz' },
  { value: 'shelley', label: 'Mary Shelley', keywords: 'frankenstein' },
  { value: 'stoker', label: 'Bram Stoker', keywords: 'dracula' },
  { value: 'lovecraft', label: 'H.P. Lovecraft', keywords: 'cthulhu' },
  { value: 'dick', label: 'Philip K. Dick', keywords: 'blade runner' },
  { value: 'gibson', label: 'William Gibson', keywords: 'neuromancer' },
  { value: 'stephenson', label: 'Neal Stephenson', keywords: 'snow crash' },
  { value: 'pratchett', label: 'Terry Pratchett', keywords: 'discworld' },
  { value: 'gaiman', label: 'Neil Gaiman', keywords: 'american gods' },
  { value: 'sanderson', label: 'Brandon Sanderson', keywords: 'stormlight mistborn' },
  { value: 'rothfuss', label: 'Patrick Rothfuss', keywords: 'kingkiller' },
  { value: 'martin', label: 'George R.R. Martin', keywords: 'game thrones' },
  { value: 'jemisin', label: 'N.K. Jemisin', keywords: 'broken earth' },
  { value: 'lecarre', label: 'John le Carré', keywords: 'spy tinker tailor' },
  { value: 'greene', label: 'Graham Greene', keywords: 'quiet american' },
  { value: 'amado', label: 'Jorge Amado', keywords: 'dona flor' },
  { value: 'lispector', label: 'Clarice Lispector', keywords: 'hour star' },
  { value: 'saramago', label: 'José Saramago', keywords: 'blindness' },
  { value: 'eco', label: 'Umberto Eco', keywords: 'name rose' },
  { value: 'calvino', label: 'Italo Calvino', keywords: 'invisible cities' },
  { value: 'levi', label: 'Primo Levi', keywords: 'survival auschwitz' },
  { value: 'kawabata', label: 'Yasunari Kawabata', keywords: 'snow country' },
  { value: 'tanizaki', label: 'Junichiro Tanizaki', keywords: 'makioka sisters' },
  { value: 'oe', label: 'Kenzaburō Ōe', keywords: 'personal matter' },
  { value: 'ishiguro', label: 'Kazuo Ishiguro', keywords: 'remains day' },
  { value: 'banville', label: 'John Banville', keywords: 'sea' },
  { value: 'mcewan', label: 'Ian McEwan', keywords: 'atonement' },
  { value: 'smith', label: 'Zadie Smith', keywords: 'white teeth' },
  { value: 'eugenides', label: 'Jeffrey Eugenides', keywords: 'middlesex' },
  { value: 'franzen', label: 'Jonathan Franzen', keywords: 'corrections' },
  { value: 'wallace', label: 'David Foster Wallace', keywords: 'infinite jest' },
  { value: 'delillo', label: 'Don DeLillo', keywords: 'white noise' },
  { value: 'pynchon', label: 'Thomas Pynchon', keywords: 'gravity rainbow' },
  { value: 'roth', label: 'Philip Roth', keywords: 'american pastoral' },
  { value: 'updike', label: 'John Updike', keywords: 'rabbit' },
  { value: 'vonnegut', label: 'Kurt Vonnegut', keywords: 'slaughterhouse five' },
  { value: 'oates', label: 'Joyce Carol Oates', keywords: 'them' },
  { value: 'munro', label: 'Alice Munro', keywords: 'short stories' },
  { value: 'martel', label: 'Yann Martel', keywords: 'life pi' },
  { value: 'yanagihara', label: 'Hanya Yanagihara', keywords: 'little life' },
  { value: 'ng', label: 'Celeste Ng', keywords: 'little fires' },
  { value: 'whitehead', label: 'Colson Whitehead', keywords: 'underground railroad' },
];

export const shortAuthorOptions: ComboboxOption[] = authorOptions.slice(0, 8);
