name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 12.5.1
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Spell Check
        run: pnpm spellcheck

      - name: Lint Markdown
        run: pnpm lint:md

      - name: Lint YAML
        run: pnpm lint:yaml

      - name: Lint GitHub Actions
        uses: raven-actions/actionlint@v2

      - name: Knip
        run: pnpm knip

  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: .config/gitleaks.toml

  build-and-test:
    runs-on: ubuntu-latest
    needs: [lint-and-check]
    environment: development
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 12.5.1
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Unit Tests by Vitest
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: ${{ vars.NODE_ENV }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: pnpm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: shotcowboystyle/universal-starter-kit

      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: -Dproject.settings=.config/sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
